// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"encoding/json"
)

type Project struct {
	ID          int32
	Name        string
	Content     json.RawMessage
	Description sql.NullString
}

type User struct {
	ID       int32
	Username string
	Password string
	ApiKey   string
}
