version: '3.9'
services:
  tnvisual:
    container_name: tnvisual
    image: silverl/tnvisual_backend:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: "host=prod_database user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - prod_database
    networks:
      - backend

  prod_database:
    container_name: prod_database
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  test_database:
    container_name: test_database
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "25432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - testdata:/var/lib/postgres/data
    networks:
      - backend

volumes:
  postgres-data:
    name: prod_data
  testdata:
    name: test_data

networks:
  backend:
    driver: bridge